/**
 * 轻量状态机
 */

const { TASK_STATES } = require("../shared/types");

const VALID_TRANSITIONS = {
  [TASK_STATES.PENDING]: [TASK_STATES.RUNNING, TASK_STATES.FAILED],
  [TASK_STATES.RUNNING]: [TASK_STATES.PLANNING, TASK_STATES.FAILED],
  [TASK_STATES.PLANNING]: [TASK_STATES.EXECUTING, TASK_STATES.FAILED],
  [TASK_STATES.EXECUTING]: [TASK_STATES.VERIFYING, TASK_STATES.FIXING, TASK_STATES.FAILED, TASK_STATES.SUCCESS],
  [TASK_STATES.VERIFYING]: [TASK_STATES.SUCCESS, TASK_STATES.FIXING, TASK_STATES.FAILED],
  [TASK_STATES.FIXING]: [TASK_STATES.EXECUTING, TASK_STATES.VERIFYING, TASK_STATES.FAILED],
  [TASK_STATES.FAILED]: [],
  [TASK_STATES.SUCCESS]: [],
};

function canTransition(from, to) {
  return (VALID_TRANSITIONS[from] || []).includes(to);
}

module.exports = { canTransition, TASK_STATES };
